site:
  name: Aikuci
  site: 'https://aikuci.web.id'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null # Grab it from google

# Default SEO metadata
metadata:
  title:
    default: Aikuci
    template: '%s — Aikuci'
  description: "\U0001F680 Discover Aikuci's impressive resume website showcasing skills and achievements."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Aikuci
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
